### ISSUE TITLE
Independent from Flutter

### ISSUE THREAD

**Issue by YTarikKalyoncu** [felixblaschke/supercharged#12]
Supercharged cool library maybe you can make it independent from flutter or make another library for pure dart.

**Comment by JasCodes** [comment]
Hey @felixblaschke 
@YTarikKalyoncu make sense. Maybe create dart version `dartcharged` and have `supercharged` depend on it 

Thx

**Comment by felixblaschke** [comment]
Ok, since I get a lot of requests I'll look into that.

**Comment by felixblaschke** [comment]
@YTarikKalyoncu I made a first try with a code generation approach.

Can you please test the package https://pub.dev/packages/supercharged_dart in a non-flutter context. It bases on supercharged 1.7.0

**Comment by felixblaschke** [comment]
Resolved with version 1.8.2
