### ISSUE TITLE
[Suggestion] About maintaining supercharged_dart

### ISSUE THREAD

**Issue by Ascenio** [felixblaschke/supercharged#13]
Instead of using code generation to check whatenever a file is flutter dependant or not you could just move all the files which are pure dart into supercharged_dart (such as Iteratable, List, Strings, etc) and just make supercharged dependent on supercharged_dart. Also, this repo could be transformed into a mono repo (for convenience) with both packages.

**Comment by felixblaschke** [comment]
Thank you for your feedback. This sounds like a good option. I will validate that.

**Comment by felixblaschke** [comment]
Resolved with version 1.8.2
