### ISSUE TITLE
Missing ability to tween more than two values per tween

### ISSUE THREAD

**Issue by benPesso** [felixblaschke/supercharged#17]
There are several cases where this would be convenient. For example, to fade a widget in and out, while also moving it from left to right, like this:

```dart
MultiTween()
  ..add('position', 0.0.tweenTo(100.0))
  ..add('opacity', 0.0.tweenTo(1.0).tweenTo(0.0))
```

**Comment by felixblaschke** [comment]
Sorry for the wrong advice. This topic is better covered at https://github.com/felixblaschke/simple_animations/issues/38
