### ISSUE TITLE
firstOrNull conflict with dart IterableExtensions

### ISSUE THREAD

**Issue by josh-burton** [felixblaschke/supercharged#20]
Dart collections have recently added a bunch of convenient extension methods like [firstOrNull](https://github.com/dart-lang/collection/blob/60e6ee2228586980826b07ec1df633bd879f42ea/lib/src/iterable_extensions.dart#L263). This now causes conflicts in my codebase as both supercharged and dart define the same extension.

Since dart now defines `firstOrNull` can this be removed from supercharged?

**Comment by felixblaschke** [comment]
Thank you for the hint. I watched into the code. Dart adapted a lot of extensions functions.

**Comment by felixblaschke** [comment]
Close this issue. Will resolve this issue in https://github.com/felixblaschke/supercharged/issues/21

**Comment by felixblaschke** [comment]
Resolved with https://pub.dev/packages/supercharged/versions/2.0.0-nullsafety.1
