### ISSUE TITLE
Add Size and Rect tweenTo extensions

### ISSUE THREAD

**Issue by shyndman** [felixblaschke/supercharged#26]
Hi there,

Any objection to the library including `Size.tweenTo` and `Rect.tweenTo` extension methods?

If not, I'm happy to send a PR.

Thanks!

**Comment by felixblaschke** [comment]
Not yet. Feel free to contribute. :-)

**Comment by felixblaschke** [comment]
Thank you for the contributions. I release it: https://pub.dev/packages/supercharged/versions/2.0.0-nullsafety.2
