### ISSUE TITLE
Consider adding actions to analyze/test incoming PRs

### ISSUE THREAD

**Issue by shyndman** [felixblaschke/supercharged#28]
Hey @felixblaschke,

Was just thinking this would be nice as a contributor. I got this set up recently on one of my repos, and it couldn't be easier:

https://github.com/madewithfelt/flutter_layout_grid/blob/main/.github/workflows/flutter-test.yml

**Comment by felixblaschke** [comment]
If I understand this correctly, there is already my Github Action that triggers for PR. But you recommend to add some static analysis to it?

**Comment by shyndman** [comment]
Ahh, I hadn't realize there were any actions.

For whatever reason, the actions didn't run against my PR. Here is my "Checks" tab: https://github.com/felixblaschke/supercharged/pull/27/checks

No checks, from the looks of it.

**Comment by felixblaschke** [comment]
I will keep an eye on it. I am currently waiting for final release of nullsafety in Flutter before investing more into the package.

**Comment by prateekmedia** [comment]
The issue is with workflow file, you need to add a similar line like below to enable tests on pr.

```yml
on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master
```

**Comment by felixblaschke** [comment]
Alright I added these lines on the workflow file.

**Comment by felixblaschke** [comment]
Thank you for testing. The PR triggered an action.
