### ISSUE TITLE
singular aliases of int->Duration extensions

### ISSUE THREAD

**Issue by myknbani** [felixblaschke/supercharged#30]
Any thoughts on the singular aliases, just like in [Rails/ActiveSupport](https://api.rubyonrails.org/classes/Numeric.html#method-i-day)?

```dart
Duration get days => Duration(days: this);
Duration get day => days; // for grammar, 1.day.ago()

Duration get hours => Duration(hours: this);
Duration get hour => hours;
```

**Comment by felixblaschke** [comment]
I already thought about that. I decided against it because it pollutes the autocomplete a lot.
The only advantage is correct grammar.

**Comment by myknbani** [comment]
Alright, we could close this then.  Thanks!
