### ISSUE TITLE
sortedByStringSC, sortedByNumSC, forEachIndexedSC are showing deprecated.

### ISSUE THREAD

**Issue by uc-dve** [felixblaschke/supercharged#32]
Please suggest now what should we use in place of it there is no suggestion showing.
![image](https://user-images.githubusercontent.com/28289763/114674093-7dce7d00-9d24-11eb-88b4-b10af8eb8f63.png)

**Comment by felixblaschke** [comment]
![marked](https://user-images.githubusercontent.com/26407468/114676652-c9bff880-9d09-11eb-9818-3822798058f5.png)

I did. You can reach the dart documentation of function by CTRL + Left Mouseclick (win/linux) or CMD + Left mouseclick (mac).

It will lead you to the migration guide: https://github.com/felixblaschke/supercharged/blob/master/migration_v2.md#adopting-darts-native-methods

**Comment by apalala-dev** [comment]
I think I didn't get how to do sorting with the collection package.

I want to compare objects with two levels : if one property is the same, compare these objects based on the second property.

Using the deprecated method from Supercharged, I would simply do:

``` dart
  myList
     .where((e) => e != null)
      .sortedBySC((a, b){
        var res = this.previousStep.compareTo(other.previousStep);
        if (res == 0) {
          return this.step.compareTo(other.step);
        } else {
          return res;
        }
      });
```
I don't need to make my object extend anything and if I have a different way of sorting later, I can just change it at that moment.

With the `collection` package, this is what I tried.

1) Extending Comparable

This is my example class :
``` dart
class SomeObject extends Comparable<SomeObject> {
  final SomeData data;
  final int previousStep;
  final int step;
  SomeObject(this.data, this.previousStep, this.step);

  @override
  int compareTo(other) {
    var res = this.previousStep.compareTo(other.previousStep);
    if (res == 0) {
      return this.step.compareTo(other.step);
    } else {
      return res;
    }
  }
}
```
Note: If I need to compare differently on some other part of my app, I will probably be annoyed.

2) Using collection package to sort
``` dart
  myList
     .where((e) => e != null)
     .sortedBy<SomeObject>((a)=> a)
```

This is not working, it tells me that the keyOf method should return a String and not an object, but I don't get what kind of String should I return ? Is it supposed to be an unique ID to make the compare method? If so, what's the purpose of implementing Comparable?

I also noticed the `sortedByCompare()` method:

> `List<String> sortedByCompare<K>(K Function(String) keyOf, int Function(K, K) compare)`
> package:collection/src/iterable_extensions.dart
> 
> Creates a sorted list of the elements of the iterable.
> 
> The elements are ordered by the [compare] [Comparator] of the property [keyOf] of the element.

However, I still don't get what is the keyOf method?

**Comment by felixblaschke** [comment]
Hi. When I planed the migration and the conflict resolution with the Dart collection package, I assumed that those methods will be a core language feature. As time has shown, the collection package needs to be added by hand. Also it's substitutes doesn't work that well, like your issue.

I will **revert** the depreciation. You can continue to use `sortedBySC()`.

I am currently in vacation, but I already planning to put some effort into supercharged package within the next months.

**Comment by felixblaschke** [comment]
I was able to revisit this issue. It looks like that all extension methods are available to any Dart/Flutter project by simply importing `package:collection/collection.dart`.

The `sortedBySC` methods can be 1:1 replaced with the `sorted` method.

Example:
```dart
class Some {
  num value;
  Some(this.value);
}

void main() {
    var arr = [Some(99), Some(3), Some(7)];

    var sorted1 = arr.sorted((a, b) => a.value.compareTo(b.value)); // possibility 1
    var sorted2 = arr.sortedBy<num>((a) => a.value); // possibility 2
}
```

I updated the [migration guide markdown file](https://github.com/felixblaschke/supercharged/blob/master/migration_v2.md#sortedby--sortedbynum--sortedbystring).

@Kobatsu 
Is this solving your use case?

**Comment by apalala-dev** [comment]
Yes, it perfectly solves my problem. I don't know if they added it recently or if I just didn't find it before...

Thank you however, I think you can close this issue!

**Comment by felixblaschke** [comment]
It was there, the whole time. I also overlooked it. I'll guess it because we focused on the "sortedBy" prefix and there are also these sortedBy methods 😄 

<img width="877" alt="Screenshot 2021-07-10 at 09 52 43" src="https://user-images.githubusercontent.com/26407468/125156257-da470a00-e164-11eb-8478-22c219fe868d.png">
