### ISSUE TITLE
Could you remove the flutter dependency?

### ISSUE THREAD

**Issue by Fasuh** [felixblaschke/supercharged#6]

**Comment by felixblaschke** [comment]
What is the advantage of removing the Flutter dependency of a Flutter package?

**Comment by Fasuh** [comment]
you could use the package in modules which dont use flutter at all, server for the instance, or some purely logical module

**Comment by felixblaschke** [comment]
Currently I'm not planning to maintain a flutter independent version of supercharged. Since maintaining a package in my spare time is time consuming i'll focus on a large core audience.
