### ISSUE TITLE
add between for DateTime

### ISSUE THREAD

**Issue by awaik** [felixblaschke/supercharged#8]
Hi Felix,

do you mind if I try to add a method "between" for DateTime? (I would like to have such a method in my project)

As before, it takes your time for checking my PRs :)

**Comment by felixblaschke** [comment]
Yes, feel free to add it. I'd like to call it `isBetween()` to match the style of DateTime methods (https://api.dart.dev/stable/2.8.4/dart-core/DateTime-class.html). I'll expect that the interval should be inclusive (`now.isBetween(now, now) // true`)

**Comment by felixblaschke** [comment]
I merged your pull request and also added some checks for null arguments. 
I also renamed `between` for int/double to `isBetween` to match the method naming.
I released it as version 1.7.0.
Thanks for your help. 👍

**Comment by awaik** [comment]
Thank you for the sharing the vision of coding :)
